branches:
  - +([0-9])?(.{+([0-9]),x}).x
  - master
  - name: develop
    prerelease: true
  - name: release/next
    prerelease: release-next
  - name: release/code-freeze
    prerelease: preview
  - name: hotfix/alpha
    prerelease: alpha
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/github"
    - successComment: false
      labels: false
      releasedLabels: false
tagFormat: "${version}"
